---
title: "Guide to add a R method"
author: "Tony Liang"
date: "2024-07-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intro

This document ilustrate step by step of adding a multiomics integration method implemented in `R` into the MESSI-pipeline running on nextflow.

In order to add such method, you need the following steps:

1. Prepare a dockerfile that describes all relevant software dependencies required by a method, with using a templated provided [here](../containers/README.md) at `r_method_base_dev.Dockerfile`. It provides important dependencies `MultiAssayExperiment`, `here` , and `docopt`.

   **Note**: If your method is too old, which requires older version of R, then you might need to create everything from scratch and not use the provided template.
   
2. Implement a preprocessing script, training script, and testing script. The inputs and output are specified down below sections

3. Declare the inputs/outputs, container used in nextflow scripts

4. Test it 


## Toy Example

We will use logistic regression (LR) as an example to act as a new method to add into MESSI. First, we need to create such dockerfile that includes packages that has LR in it, which is alredy in base R accessed by `stats::glm()`. Just for the sake of demonstration, I included a snippet of Dockefile.


```{bash, eval=FALSE}
# This is the dockerfile for logistic regression
# 
# This let us use the template docker image as base
# to skip over installation/compilation of important deps
# like docopt, here, and MultiAssayExperiment
FROM tonyliang19/r_method_base_dev

# Then install the stats pkg just for demo purpose
# normally, it is automatically included in baseR
# NOTE: The "" and '' quotation marks are needed
RUN Rscript -e "install.packages('stats')"
```


### Implementing the preprocessing step

Now, this comes a bit of hard part, since it relates with Nextflow logic and making concepts complicated. 

First, we define the input to be a path to MultiAssayExperiment data directory, which it contains a file of `experiments.h5` and `mae.rds`. 


> TODO: Need to explain better here? and introduce the nextflow concept earlier

